services:
  api:
    container_name: study-api
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
  redis:
    container_name: study-redis
    hostname: study-redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  postgres:
    container_name: study-db
    hostname: study-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  docker-nest-postgres:
